# Generated by Django 4.2.11 on 2024-03-30 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cus_id', models.AutoField(primary_key=True, serialize=False)),
                ('cus_name', models.TextField(max_length=50)),
                ('cus_email', models.TextField(max_length=255)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('prefer_type', models.CharField(choices=[('live', 'live'), ('concert', 'concert'), ('opera', 'opera'), ('show', 'show')], max_length=20)),
                ('cus_password', models.TextField()),
                ('bill_address', models.TextField(max_length=255)),
                ('cus_phone', models.TextField()),
            ],
            options={
                'db_table': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='Event_info',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.TextField(max_length=50)),
                ('event_date', models.DateTimeField()),
                ('event_description', models.TextField(max_length=5000)),
                ('event_address', models.TextField(max_length=50)),
                ('event_image', models.ImageField(upload_to='static/')),
                ('event_type', models.CharField(choices=[('Concert', 'Concert'), ('live', 'live'), ('opera', 'opera')], max_length=20)),
                ('ticket_amount', models.IntegerField()),
                ('last_selling_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'Event_info',
            },
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('org_id', models.AutoField(primary_key=True, serialize=False)),
                ('org_email', models.TextField(max_length=255)),
                ('org_password', models.TextField()),
                ('company_name', models.TextField(max_length=255)),
                ('company_address', models.TextField(max_length=255)),
                ('org_phone', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Organizer',
            },
        ),
        migrations.CreateModel(
            name='Ticket_info',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('ticket_type', models.IntegerField()),
                ('ticket_amount', models.IntegerField()),
                ('ticket_price', models.IntegerField()),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='event_system_app.event_info')),
            ],
            options={
                'db_table': 'Ticket_info',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('reservation_time', models.DateTimeField(blank=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='event_system_app.customer')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='event_system_app.event_info')),
            ],
            options={
                'db_table': 'Reservation',
            },
        ),
        migrations.CreateModel(
            name='Reply_org',
            fields=[
                ('reply_id', models.AutoField(primary_key=True, serialize=False)),
                ('reply_org', models.TextField()),
                ('reply_time', models.DateTimeField()),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='event_system_app.event_info')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='event_system_app.organizer')),
            ],
            options={
                'db_table': 'Reply_org',
            },
        ),
        migrations.AddField(
            model_name='event_info',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='event_system_app.organizer'),
        ),
        migrations.CreateModel(
            name='Comment_cus',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_cus', models.TextField(max_length=500)),
                ('comment_time', models.DateTimeField()),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='event_system_app.customer')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='event_system_app.event_info')),
            ],
            options={
                'db_table': 'Comment_cus',
            },
        ),
    ]
