# Generated by Django 4.2.11 on 2024-04-08 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_system_app', '0007_comment_cus_comment_image_url_comment_cus_event_rate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='account_balence',
            new_name='account_balance',
        ),
        migrations.AddField(
            model_name='reply_org',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='event_system_app.comment_cus'),
        ),
        migrations.AlterField(
            model_name='reply_org',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event_system_app.event_info'),
        ),
        migrations.AlterField(
            model_name='reply_org',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event_system_app.organizer'),
        ),
    ]
