# Generated by Django 5.0.3 on 2024-04-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_system_app', '0013_customer_prefer_tags_event_info_event_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment_cus',
            name='likes',
            field=models.IntegerField(default=0, help_text='Number of likes for the event'),
        ),
        migrations.AddField(
            model_name='customer',
            name='age_area',
            field=models.CharField(choices=[('18-25', '18-25 Years'), ('26-35', '26-35 Years'), ('36-45', '36-45 Years'), ('46-55', '46-55 Years'), ('56-65', '56-65 Years'), ('65+', '65+ Years')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ticket_info',
            name='ticket_seat_pool',
            field=models.TextField(blank=True, default=''),
        ),
    ]
