# Generated by Django 4.2.11 on 2024-04-16 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment_cus',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_rate', models.IntegerField(null=True)),
                ('comment_cus', models.TextField(max_length=500)),
                ('comment_time', models.DateTimeField()),
                ('comment_image_url', models.TextField(blank=True, default=None, null=True)),
                ('likes', models.IntegerField(default=0, help_text='Number of likes for the event')),
            ],
            options={
                'db_table': 'Comment_cus',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cus_id', models.AutoField(primary_key=True, serialize=False)),
                ('cus_name', models.TextField(max_length=50)),
                ('cus_email', models.TextField(max_length=255)),
                ('gender', models.TextField(max_length=20, null=True)),
                ('prefer_type', models.TextField(max_length=20, null=True)),
                ('age_area', models.TextField(max_length=20, null=True)),
                ('prefer_tags', models.TextField(blank=True, null=True)),
                ('cus_password', models.TextField()),
                ('bill_address', models.TextField(max_length=255)),
                ('cus_phone', models.TextField()),
                ('account_balance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=500)),
            ],
            options={
                'db_table': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='Event_info',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.TextField(max_length=50)),
                ('event_date', models.DateTimeField()),
                ('event_description', models.TextField(max_length=5000)),
                ('event_address', models.TextField(max_length=50)),
                ('event_tags', models.TextField(blank=True, null=True)),
                ('event_image_url', models.TextField(null=True)),
                ('event_type', models.CharField(choices=[('Concert', 'Concert'), ('live', 'live'), ('opera', 'opera')], max_length=20)),
                ('event_last_selling_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'Event_info',
            },
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('org_id', models.AutoField(primary_key=True, serialize=False)),
                ('org_email', models.TextField(max_length=255)),
                ('org_password', models.TextField()),
                ('company_name', models.TextField(max_length=255)),
                ('company_address', models.TextField(max_length=255)),
                ('org_phone', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Organizer',
            },
        ),
        migrations.CreateModel(
            name='Ticket_info',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('ticket_type', models.TextField()),
                ('ticket_name', models.TextField(blank=True, default='Special reserving area')),
                ('ticket_seat_pool', models.TextField(blank=True, default='')),
                ('ticket_amount', models.IntegerField()),
                ('ticket_price', models.IntegerField()),
                ('ticket_remain', models.IntegerField(default=0)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='event_system_app.event_info')),
            ],
            options={
                'db_table': 'Ticket_info',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('reservation_time', models.DateTimeField(blank=True)),
                ('amount', models.IntegerField(blank=True, default=0)),
                ('reserve_seat', models.TextField(blank=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='event_system_app.customer')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='event_system_app.event_info')),
                ('ticket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='event_system_app.ticket_info')),
            ],
            options={
                'db_table': 'Reservation',
            },
        ),
        migrations.CreateModel(
            name='Reply_org',
            fields=[
                ('reply_id', models.AutoField(primary_key=True, serialize=False)),
                ('reply_org', models.TextField()),
                ('reply_time', models.DateTimeField()),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='event_system_app.comment_cus')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event_system_app.event_info')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event_system_app.organizer')),
            ],
            options={
                'db_table': 'Reply_org',
            },
        ),
        migrations.CreateModel(
            name='LikeCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_system_app.comment_cus')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_system_app.customer')),
            ],
            options={
                'db_table': 'Like',
            },
        ),
        migrations.AddField(
            model_name='event_info',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='event_system_app.organizer'),
        ),
        migrations.AddField(
            model_name='comment_cus',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='event_system_app.customer'),
        ),
        migrations.AddField(
            model_name='comment_cus',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='event_system_app.event_info'),
        ),
        migrations.CreateModel(
            name='Cancel',
            fields=[
                ('cancel_id', models.AutoField(primary_key=True, serialize=False)),
                ('cancel_time', models.DateTimeField()),
                ('cancel_amount', models.IntegerField(default=0)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='event_system_app.customer')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='event_system_app.event_info')),
                ('ticket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='event_system_app.ticket_info')),
            ],
            options={
                'db_table': 'Cancel',
            },
        ),
    ]
