# Generated by Django 4.2.11 on 2024-04-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_system_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='prefer_type',
            field=models.CharField(choices=[('live', 'live'), ('concert', 'concert'), ('opera', 'opera'), ('show', 'show')], max_length=20, null=True),
        ),
    ]
