# Generated by Django 4.2.11 on 2024-04-06 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_system_app', '0002_alter_customer_gender_alter_customer_prefer_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_info',
            name='ticket_amount',
        ),
    ]
