# Generated by Django 4.2.11 on 2024-04-06 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_system_app', '0003_remove_event_info_ticket_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket_info',
            name='ticket_remain',
            field=models.IntegerField(default=0),
        ),
    ]
