# Generated by Django 4.2.11 on 2024-04-06 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_system_app', '0005_rename_last_selling_date_event_info_event_last_selling_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket_info',
            name='ticket_type',
            field=models.TextField(),
        ),
    ]
