# Generated by Django 4.2.11 on 2024-04-06 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_system_app', '0006_alter_ticket_info_ticket_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment_cus',
            name='comment_image_url',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='comment_cus',
            name='event_rate',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='account_balence',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=500),
        ),
        migrations.AddField(
            model_name='reservation',
            name='amount',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='reservation',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='event_system_app.ticket_info'),
        ),
    ]
