# Generated by Django 4.2.11 on 2024-04-08 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_system_app', '0008_rename_account_balence_customer_account_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket_info',
            name='ticket_name',
            field=models.TextField(blank=True, default='Special reserving area'),
        ),
    ]
