# Generated by Django 4.2.11 on 2024-04-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_system_app', '0009_ticket_info_ticket_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reserve_seat',
            field=models.TextField(blank=True),
        ),
    ]
