# Generated by Django 4.2.11 on 2024-04-08 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_system_app', '0010_reservation_reserve_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reserve_state',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Cancel',
            fields=[
                ('cancel_id', models.AutoField(primary_key=True, serialize=False)),
                ('cancel_time', models.DateTimeField()),
                ('cancel_amount', models.IntegerField(default=0)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='event_system_app.customer')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='event_system_app.event_info')),
                ('ticket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='event_system_app.ticket_info')),
            ],
        ),
    ]
