# Generated by Django 4.2.11 on 2024-04-08 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_system_app', '0011_reservation_reserve_state_cancel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='reserve_state',
        ),
        migrations.AlterModelTable(
            name='cancel',
            table='Cancel',
        ),
    ]
