# Generated by Django 4.2.11 on 2024-04-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_system_app', '0012_remove_reservation_reserve_state_alter_cancel_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='prefer_tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event_info',
            name='event_tags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
