# Generated by Django 5.0.4 on 2024-04-13 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_system_app', '0014_comment_cus_likes_customer_age_area_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_system_app.comment_cus')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_system_app.customer')),
            ],
            options={
                'db_table': 'Like',
                'unique_together': {('customer', 'comment')},
            },
        ),
    ]
