# Generated by Django 4.2.11 on 2024-04-13 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_system_app', '0015_customer_age_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment_cus',
            name='likes',
            field=models.IntegerField(default=0, help_text='Number of likes for the event'),
        ),
        migrations.CreateModel(
            name='LikeCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_system_app.comment_cus')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_system_app.customer')),
            ],
            options={
                'db_table': 'Like',
                'unique_together': {('customer', 'comment')},
            },
        ),
    ]
