# Generated by Django 5.0.4 on 2024-04-14 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_system_app', '0015_likecheck'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likecheck',
            unique_together=set(),
        ),
    ]
