# Generated by Django 5.0.3 on 2024-04-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event_system_app", "0017_alter_customer_age_area_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="age_area",
            field=models.TextField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="gender",
            field=models.TextField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="prefer_type",
            field=models.TextField(max_length=20, null=True),
        ),
    ]
